name: Tests on push

on: [push]

jobs:
  etl:
    name: ETL integration tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
      - name: Install requirements
        run: pip install -r requirements.txt
        working-directory: ./etl
  api:
    name: API unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
      - name: Install requirements
        run: pip install -r requirements.txt
        working-directory: ./api
