name: Tests on push

on: [push]

jobs:
  etl:
    name: ETL integration tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
      - name: Install requirements
        run: pip install -r requirements.txt -r requirements-dev.txt
        working-directory: ./etl
      - name: Run end-to-end tests
        run: pytest tests/
        working-directory: ./etl
  api:
    name: API unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
      - name: Install requirements
        run: pip install -r requirements.txt -r requirements-dev.txt
        working-directory: ./api
      - name: Run unit tests
        run: pytest --cov-report term-missing --cov=products_api --cov-fail-under=95 tests/
        working-directory: ./api
